version: '3.3'
services:
    # ----------------------------------------------------------------------------
    # Backend
    # ----------------------------------------------------------------------------
    backend:
        container_name: backend
        build:
            context: .
            dockerfile: ./dockerfile_backend
        volumes:
            - ./backend/.:/app
            - /app/node_modules
        ports:
            - "8080:8080"
        env_file:
            - .env
        depends_on:
            - postgres
    # ----------------------------------------------------------------------------
    # Database
    # ----------------------------------------------------------------------------
    postgres:
        container_name: postgres
        image: postgres:12
        restart: always
        environment:
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
            POSTGRES_USER: ${POSTGRES_USER}
            POSTGRES_DB: ${POSTGRES_DATABASE}
            PG_DATA: /var/lib/postgresql/data
        env_file:
            - .env
        ports:
            - "5432:5432"
        volumes:
            - pgdata:/var/lib/postgresql/data
    # ----------------------------------------------------------------------------
    # Pgadmin
    # ----------------------------------------------------------------------------
    pgadmin:
        container_name: pgadmin_container
        image: dpage/pgadmin4
        environment:
            PGADMIN_DEFAULT_EMAIL: ${PGADMIN_EMAIL}
            PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PASSWORD}
            PGADMIN_CONFIG_SERVER_MODE: 'False'
        volumes:
             - pgadmin:/root/.pgadmin
        ports:
            - "5050:80"
        restart: unless-stopped
    # ----------------------------------------------------------------------------
    # Frontend
    # ----------------------------------------------------------------------------
    frontend:
        build:
            context: .
            dockerfile: ./dockerfile_frontend
        volumes:
          - ./frontend:/app
          - /app/node_modules
        env_file:
          - .env
        ports:
          - "3000:3000"
        depends_on:
          - backend
volumes:
    pgdata:
    pgadmin: